services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=jakewaldron
      - PGUSER="$POSTGRES_USER"
      - POSTGRES_DB=return_scanning
      - PGDATABASE="$POSTGRES_DB"
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/dbStuff/:/app/server/dbStuff/
  server:
    build: ./server
    ports:
      - '8080:8080'
    volumes:
      - ./server/:/app/server
      - /app/server/node_modules
    depends_on:
      - postgres
    command: sh -c './wait-for postgres:5432 -- npm start'
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/client/src
      - /app/client/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  postgres-data: