services:

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/dbStuff/:/app/server/dbStuff/

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    env_file:
      - server.env
    volumes:
      - ./server/:/app/server
      - /app/server/node_modules
    depends_on:
      - postgres
    command: sh -c '/app/server/wait-for postgres:5432 -- npm start'

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_API_ENDPOINT: "http://localhost:8080"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
      
volumes:
  postgres-data:


